# DuckDB config reference:
config:
  send_anonymous_usage_stats: False
  use_colors: True
dbt_project:
  target: silver
  outputs:
    silver:
      type: duckdb
      path: data.duckdb
      extensions:
        - httpfs
        - parquet
      settings:
        s3_access_key_id: minioadmin
        s3_secret_access_key: minioadmin
        s3_endpoint: host.docker.internal:9000
        s3_region: us-east-1
        s3_url_style: path
        http_keep_alive: false
        s3_use_ssl: false
      threads: 1
      external_root: s3://de-data-silver
    gold:
      type: duckdb
      path: data.duckdb
      extensions:
        - httpfs
        - parquet
      settings:
        s3_access_key_id: minioadmin
        s3_secret_access_key: minioadmin
        s3_endpoint: host.docker.internal:9000
        s3_region: us-east-1
        s3_url_style: path
        http_keep_alive: false
        s3_use_ssl: false
      threads: 1
      external_root: s3://de-data-gold