"""Superset config."""
import os

REDIS_PORT = os.getenv("SUPERSET_REDIS_PORT")
REDIS_HOST = "de-redis"

CACHE_CONFIG = {
    "CACHE_TYPE": "redis",
    "CACHE_DEFAULT_TIMEOUT": 300,
    "CACHE_REDIS_HOST": REDIS_HOST,
    "CACHE_REDIS_PORT": REDIS_PORT,
    "CACHE_REDIS_DB": 1,
    "CACHE_REDIS_URL": f"redis://{REDIS_HOST}:{REDIS_PORT}/1",
}

POSTGRES_USER = os.getenv("POSTGRES_USER")
POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD")
POSTGRES_PORT = os.getenv("POSTGRES_PORT")
SUPERSET_POSTGRES_DB = os.getenv("SUPERSET_POSTGRES_DB")
SQLALCHEMY_DATABASE_URI = f"postgresql+psycopg2://{POSTGRES_USER}:{POSTGRES_PASSWORD}@de-postgres-db:5432/{SUPERSET_POSTGRES_DB}"  # noqa: E501
SQLALCHEMY_TRACK_MODIFICATIONS = True
